pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir ('csy3056-as1-scaffold') {
                    echo 'Installing dependencies'
                    bat 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir ('csy3056-as1-scaffold') {
                    echo 'Running tests'
                    bat 'pytest'
                }
            }
        }
    }
}