# Tells pytest to read current file and adds . to the path before importing modules, allowing
# pytest to find and import the project files when running tests
# without this, pytest in the virtial enviromnment when ran, it is unable to find project files and fails
[pytest]
pythonpath = .